export const AllowedTags = {
  "action" : "ACTION",
  "adventure" : "ADVENTURE",
  "casual" : "CASUAL",
  "experimental" : "EXPERIMENTAL",
  "puzzle" : "PUZZLE",
  "racing" : "RACING",
  "rpg" : "RPG",
  "simulation" : "SIMULATION",
  "sports" : "SPORTS",
  "strategy" : "STRATEGY",
  "tabletop" : "TABLETOP",
  "building" : "BUILDING",
  "card game" : "CARD_GAME",
  "character action" : "CHARACTER_ACTION",
  "farming sim" : "FARMING_SIM",
  "fighting" : "FIGHTING",
  "open world" : "OPEN_WORLD",
  "platformer" : "PLATFORMER",
  "rhythm" : "RHYTHM",
  "roguelike" : "ROGUELIKE",
  "rts" : "RTS",
  "shooter" : "SHOOTER",
  "stealth" : "STEALTH",
  "survival" : "SURVIVAL",
  "visual novel" : "VISUAL_NOVEL",
  "hack and slash" : "HACK_AND_SLASH",
  "horror" : "HORROR",
  "jrpg" : "JRPG",
  "souls-like" : "SOULSLIKE",
  "turn-based combat" : "TURNBASED_COMBAT",
  "indie" : "INDIE",
  "relaxing" : "RELAXING"
}