export const AllowedTags = {
  "Action" : "ACTION",
  "Adventure" : "ADVENTURE",
  "Casual" : "CASUAL",
  "Experimental" : "EXPERIMENTAL",
  "Puzzle" : "PUZZLE",
  "Racing" : "RACING",
  "RPG" : "RPG",
  "Simulation" : "SIMULATION",
  "Sports" : "SPORTS",
  "Strategy" : "STRATEGY",
  "Tabletop" : "TABLETOP",
  "Building" : "BUILDING",
  "Card Game" : "CARD_GAME",
  "Character Action" : "CHARACTER_ACTION",
  "Farming Sim" : "FARMING_SIM",
  "Fighting" : "FIGHTING",
  "Open World" : "OPEN_WORLD",
  "Platformer" : "PLATFORMER",
  "Rhythm" : "RHYTHM",
  "Roguelike" : "ROGUELIKE",
  "RTS" : "RTS",
  "Shooter" : "SHOOTER",
  "Stealth" : "STEALTH",
  "Survival" : "SURVIVAL",
  "Visual Novel" : "VISUAL_NOVEL",
  "Hack and Slash" : "HACK_AND_SLASH",
  "Horror" : "HORROR",
  "JRPG" : "JRPG",
  "Souls-like" : "SOULSLIKE",
  "Turn-Based Combat" : "TURNBASED_COMBAT",
  "Indie" : "INDIE",
  "Relaxing" : "RELAXING"
}