package com.gametracker.backend.enums;

public enum AllowedTags {
    ACTION,
    ADVENTURE,
    CASUAL,
    EXPERIMENTAL,
    PUZZLE,
    RACING,
    RPG,
    SIMULATION,
    SPORTS,
    STRATEGY,
    TABLETOP,
    BUILDING,
    CARD_GAME,
    CHARACTER_ACTION,
    FARMING_SIM,
    FIGHTING,
    OPEN_WORLD,
    PLATFORMER,
    RHYTHM,
    ROGUELIKE,
    RTS,
    SHOOTER,
    STEALTH,
    SURVIVAL,
    VISUAL_NOVEL,
    HACK_AND_SLASH,
    HORROR,
    JRPG,
    SOULSLIKE,
    TURNBASED_COMBAT,
    INDIE,
    RELAXING
}